### ISSUE TITLE
perf: Server Actions を tRPC に移行する

### ISSUE THREAD

**Issue by exKAZUu** [exKAZUu-Research/trace-dojo#100]
Server Actionsは同時に一つの関数しか実行できないという制約があるため、
https://github.com/exKAZUu-Research/trace-dojo/blob/main/src/app/lib/actions.ts を全てtRPCに書き換える。
あわせて、zodで引数を検証するようにする。

**Comment by exKAZUu** [comment]
@hishiwat サーバーコンポーネントのみから呼ばれている関数は、紛らわしいので、別のフォルダのファイルに移動してほしい。現在使われていない関数は削除してください。

**Comment by hishiwat** [comment]
@exKAZUu サーバーコンポーネントとクライアントコンポーネントの両方から呼ばれている関数の場合はどうすればいいでしょうか。

**Comment by exKAZUu** [comment]
@hishiwat まず普通の関数を定義して、tRPCからはただその関数を呼ぶ。サーバーからは直接関数を呼ぶ。
