### ISSUE TITLE
feat: レクチャーページを新設して、コースから直接問題ページへのリンクをはらない

### ISSUE THREAD

**Issue by exKAZUu** [exKAZUu-Research/trace-dojo#101]
今は各科目（コース）ページ (e.g., https://trace-dojo-staging.fly.dev/courses/tuBeginner1) に、全回の全問題が表示されている。
このページを変更して、コースページは各回（レクチャー）ページにリンクをはる形式にする。

各回ページのURLを推測できないような複雑なものにする。例えば、

1. `https://trace-dojo-staging.fly.dev/courses/tuBeginner1/lecture1-<UUIDv4>`
2. `https://trace-dojo-staging.fly.dev/courses/tuBeginner1/lecture2-<UUIDv4>`

のようにUUIDv4を含める。このUUIDv4部分は `const UUIDs = ['abc', 'def', ...]` のようなソースコード中の定数に定義する。

さらに、コースページで表示する各回（レクチャー）ページのリンクは、一度開いたことがある各回（レクチャー）ページのみに限定する。
各回（レクチャー）ページのURLは講義資料で開示することにする。

**Comment by hishiwat** [comment]
@exKAZUu 問題ページのリンクは http://localhost:3000/courses/tuBeginner1/languageid/straight のようになっているのですが、`languageid`は削除しても大丈夫ですか。
