### ISSUE TITLE
fix: 問題を完了した後に問題一覧画面に戻りやすくする

### ISSUE THREAD

**Issue by reminjp** [exKAZUu-Research/trace-dojo#126]
現状では、「正解」の旨のダイアログを閉じた後、自分でリンクかブラウザの戻るボタンをクリックして遷移しなければならない。
例えば、ダイアログに問題一覧画面に戻るボタンが設置されていれば、1操作で達成できる。

**Comment by exKAZUu** [comment]
修正した
